### ISSUE TITLE
Port to a compiled language?

### ISSUE THREAD

**Issue by YashMathur** [fantastic-kit/fantastic-kit#25]
Using ruby to build this may not be the best thing because - 
1) users would have to install ruby
2) any gems that you end up using to be installed
3) this entire repo cloned
4) (not sure if valid) if they're working on a project with ruby version 1.8 and you're using some of ruby 2.6's features, they may not be able to use `fk`.

Since you're in a fairly early stage of the project, maybe consider switching to a compiled language?

**Comment by Azhng** [comment]
Interesting idea, I used started using Ruby since it just came to me most naturally. 

For 1 and 4, I think one of the possibilities is for us to directly ship a Ruby binary with the installations so we have the full control of the Ruby version that's going to be used. Alternatively we can have the installation script to install a specific ruby version on user's system unless user opt out. 

For 2, currently my plan is to trying me best to avoid using any gem when possible, though this is still in the early stage so it's hard to say if it even possible. 

For 3, the installation script currently just clone the repo with `--depth=1`, the subsequent update is just a simple `git pull`. There are some open source project is currently maintained this way (e.g. Homebrew and oh-my-zsh, and I think this is still a viable method for maintaining releases) 

However, like you said this project is still in the early stage, I'm still open to the idea of using a compiled language. Though it feels like we have limited options since we need fantastic-kit to boot fast (so probably avoiding JIT languages and the ones with heavy runtime, e.g. Java and C#).

That really leaves us with C/C++, Golang and Rust.

**Comment by Azhng** [comment]
Any one else has strong opinions on this?

**Comment by arora-aman** [comment]
This might be a one time thing but we would have to compile on the users computer else we need to provide binaries for all common architectures. 

For C/C++ you would need to make sure libcurl and libjson are either installed, or statically linked in our binaries. 

We are currently using YAML to support and luckily there is a c++ parser https://github.com/jbeder/yaml-cpp

I haven't worked with Go/Rust to make any comments.

**Comment by 9at8** [comment]
No strong opinions here.

If we use a compiled language, then we need to provide the compiled binaries for all architectures, etc. Maybe there's a build system for that? idk ¯\\\_(ツ)\_/¯

If we *are* switching, then I vote for Rust!

**Comment by 9at8** [comment]
For adding support for fish, I had to reimplement a lot of things again. We shouldn't have to do this, as this will lead to inconsistent behavior across shells.

On top of that, writing code in fish, or bash, is not a pleasant experience. To top it up, we want to support auto complete for these shells too.

I say we use something like https://github.com/clap-rs/clap to build fantastic kit.

This means we would have to rewrite everything in Rust, but we will get a lot of features for free, along with a consistent implementation across different shells.

**Comment by Azhng** [comment]
I do agree that Rust is a way superior language than Bash when it comes to building fantastic-kit, and re-implementing same functionalities in different shell does suck. If we do want to re-implement a fully featured `dev` clone, Rust is probably a way better solution.  
However, even back in Shopify I personally use less than 20% of all the functionalities provided by `dev`. My original intention of creating fantastic-kit was to recreate that 20% of the functionalities (cd/clone/pr etc. with auto-completion and support for yaml project file) of `dev` that are now basically my muscle memories. 
My original vision for fantastic-kit is a simple, small but still extensible command line tool that simply just makes my life easier, and hence Ruby + Bash becomes my go to choice. 
Nevertheless, if anyone want to port fantastic-kit to a compiled language, definitely feel free to submit PRs and I will be more than happy to approve it.

**Comment by Azhng** [comment]
Just to clarify, IMHO Rust is definitely a better choice than Shell + Ruby. But for me, the scope of the fantastic-kit itself doesn't really justify the cost of rewriting it in Rust.

**Comment by YashMathur** [comment]
@Azhng agreed

**Comment by Azhng** [comment]
Close it for now
